// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/bgg.proto

package bggpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NONE      Status = 0
	Status_OK        Status = 1
	Status_NOT_FOUND Status = 2
	Status_ERROR     Status = 3
)

var Status_name = map[int32]string{
	0: "NONE",
	1: "OK",
	2: "NOT_FOUND",
	3: "ERROR",
}

var Status_value = map[string]int32{
	"NONE":      0,
	"OK":        1,
	"NOT_FOUND": 2,
	"ERROR":     3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{0}
}

type Game struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year                 uint64   `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Rank                 uint64   `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Average              float64  `protobuf:"fixed64,5,opt,name=average,proto3" json:"average,omitempty"`
	BayesAverage         float64  `protobuf:"fixed64,6,opt,name=bayes_average,json=bayesAverage,proto3" json:"bayes_average,omitempty"`
	UsersRated           uint64   `protobuf:"varint,7,opt,name=users_rated,json=usersRated,proto3" json:"users_rated,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Thumbnail            string   `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{0}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Game) GetYear() uint64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Game) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Game) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *Game) GetBayesAverage() float64 {
	if m != nil {
		return m.BayesAverage
	}
	return 0
}

func (m *Game) GetUsersRated() uint64 {
	if m != nil {
		return m.UsersRated
	}
	return 0
}

func (m *Game) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Game) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

type GetGamesListRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGamesListRequest) Reset()         { *m = GetGamesListRequest{} }
func (m *GetGamesListRequest) String() string { return proto.CompactTextString(m) }
func (*GetGamesListRequest) ProtoMessage()    {}
func (*GetGamesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{1}
}

func (m *GetGamesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGamesListRequest.Unmarshal(m, b)
}
func (m *GetGamesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGamesListRequest.Marshal(b, m, deterministic)
}
func (m *GetGamesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGamesListRequest.Merge(m, src)
}
func (m *GetGamesListRequest) XXX_Size() int {
	return xxx_messageInfo_GetGamesListRequest.Size(m)
}
func (m *GetGamesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGamesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGamesListRequest proto.InternalMessageInfo

func (m *GetGamesListRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetGamesListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetGamesListResponse struct {
	Ordinal              uint32   `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Game                 *Game    `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGamesListResponse) Reset()         { *m = GetGamesListResponse{} }
func (m *GetGamesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetGamesListResponse) ProtoMessage()    {}
func (*GetGamesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{2}
}

func (m *GetGamesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGamesListResponse.Unmarshal(m, b)
}
func (m *GetGamesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGamesListResponse.Marshal(b, m, deterministic)
}
func (m *GetGamesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGamesListResponse.Merge(m, src)
}
func (m *GetGamesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetGamesListResponse.Size(m)
}
func (m *GetGamesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGamesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGamesListResponse proto.InternalMessageInfo

func (m *GetGamesListResponse) GetOrdinal() uint32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *GetGamesListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetGamesListResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type FindGameByIdRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGameByIdRequest) Reset()         { *m = FindGameByIdRequest{} }
func (m *FindGameByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindGameByIdRequest) ProtoMessage()    {}
func (*FindGameByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{3}
}

func (m *FindGameByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGameByIdRequest.Unmarshal(m, b)
}
func (m *FindGameByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGameByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindGameByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGameByIdRequest.Merge(m, src)
}
func (m *FindGameByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindGameByIdRequest.Size(m)
}
func (m *FindGameByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGameByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindGameByIdRequest proto.InternalMessageInfo

func (m *FindGameByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindGameByIdResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=bgg.Status" json:"status,omitempty"`
	Game                 *Game    `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGameByIdResponse) Reset()         { *m = FindGameByIdResponse{} }
func (m *FindGameByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindGameByIdResponse) ProtoMessage()    {}
func (*FindGameByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e58b8a4c56c4ea6, []int{4}
}

func (m *FindGameByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGameByIdResponse.Unmarshal(m, b)
}
func (m *FindGameByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGameByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindGameByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGameByIdResponse.Merge(m, src)
}
func (m *FindGameByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindGameByIdResponse.Size(m)
}
func (m *FindGameByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGameByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindGameByIdResponse proto.InternalMessageInfo

func (m *FindGameByIdResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindGameByIdResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NONE
}

func (m *FindGameByIdResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func init() {
	proto.RegisterEnum("bgg.Status", Status_name, Status_value)
	proto.RegisterType((*Game)(nil), "bgg.Game")
	proto.RegisterType((*GetGamesListRequest)(nil), "bgg.GetGamesListRequest")
	proto.RegisterType((*GetGamesListResponse)(nil), "bgg.GetGamesListResponse")
	proto.RegisterType((*FindGameByIdRequest)(nil), "bgg.FindGameByIdRequest")
	proto.RegisterType((*FindGameByIdResponse)(nil), "bgg.FindGameByIdResponse")
}

func init() { proto.RegisterFile("messages/bgg.proto", fileDescriptor_4e58b8a4c56c4ea6) }

var fileDescriptor_4e58b8a4c56c4ea6 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x5f, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xc4, 0x71, 0xea, 0x49, 0x52, 0x59, 0xd3, 0x80, 0x16, 0x04, 0x22, 0x72, 0x85,
	0x14, 0xf1, 0x50, 0x50, 0xe0, 0x02, 0x04, 0xd2, 0x08, 0x81, 0x62, 0x69, 0x0b, 0x2f, 0xbc, 0x44,
	0x6b, 0x3c, 0x35, 0xa6, 0xfe, 0x13, 0x76, 0xd7, 0x95, 0x72, 0x22, 0xee, 0xc5, 0x49, 0xd0, 0xae,
	0x6d, 0xd1, 0x96, 0x48, 0xbc, 0xcd, 0xfc, 0x66, 0xfc, 0xed, 0xcc, 0x37, 0x32, 0x60, 0x41, 0x4a,
	0x89, 0x94, 0xd4, 0xcb, 0x38, 0x4d, 0xcf, 0x77, 0xb2, 0xd2, 0x15, 0xf6, 0xe3, 0x34, 0x0d, 0x7f,
	0x3b, 0xe0, 0xae, 0x45, 0x41, 0x78, 0x02, 0xbd, 0x2c, 0x61, 0xce, 0xcc, 0x99, 0xbb, 0xbc, 0x97,
	0x25, 0x88, 0xe0, 0x96, 0xa2, 0x20, 0xd6, 0x9b, 0x39, 0x73, 0x9f, 0xdb, 0xd8, 0xb0, 0x3d, 0x09,
	0xc9, 0xfa, 0xb6, 0xcb, 0xc6, 0x86, 0x49, 0x51, 0x5e, 0x33, 0xb7, 0x61, 0x26, 0x46, 0x06, 0x43,
	0x71, 0x43, 0x52, 0xa4, 0xc4, 0x06, 0x33, 0x67, 0xee, 0xf0, 0x2e, 0xc5, 0x33, 0x98, 0xc4, 0x62,
	0x4f, 0x6a, 0xdb, 0xd5, 0x3d, 0x5b, 0x1f, 0x5b, 0xf8, 0xb6, 0x6d, 0x7a, 0x06, 0xa3, 0x5a, 0x91,
	0x54, 0x5b, 0x29, 0x34, 0x25, 0x6c, 0x68, 0x95, 0xc1, 0x22, 0x6e, 0x08, 0x06, 0xd0, 0xaf, 0x65,
	0xce, 0x8e, 0xed, 0x68, 0x26, 0xc4, 0x27, 0xe0, 0xeb, 0xef, 0x75, 0x11, 0x97, 0x22, 0xcb, 0x99,
	0x6f, 0xf9, 0x5f, 0x10, 0xbe, 0x83, 0xd3, 0x35, 0x69, 0xb3, 0xa6, 0xfa, 0x94, 0x29, 0xcd, 0xe9,
	0x67, 0x4d, 0x4a, 0xe3, 0x43, 0xf0, 0xaa, 0xab, 0x2b, 0x45, 0xda, 0xae, 0x3d, 0xe1, 0x6d, 0x86,
	0x53, 0x18, 0xe4, 0x59, 0x91, 0x69, 0xbb, 0xfb, 0x84, 0x37, 0x49, 0x48, 0x30, 0xbd, 0x2b, 0xa2,
	0x76, 0x55, 0xa9, 0xc8, 0x2c, 0x5b, 0xc9, 0x24, 0x2b, 0x45, 0xde, 0xca, 0x74, 0xa9, 0xd1, 0xd1,
	0x95, 0x16, 0x79, 0xa7, 0x63, 0x13, 0x7c, 0x0a, 0x6e, 0x6a, 0x8c, 0x35, 0x26, 0x8e, 0x16, 0xfe,
	0xb9, 0x39, 0x88, 0x51, 0xe5, 0x16, 0x87, 0xcf, 0xe1, 0xf4, 0x22, 0x2b, 0x13, 0x43, 0x96, 0xfb,
	0x0f, 0x49, 0x37, 0xeb, 0xbd, 0xf3, 0x84, 0x3f, 0x60, 0x7a, 0xb7, 0xad, 0x9d, 0xe6, 0xfe, 0x19,
	0xcf, 0xc0, 0x53, 0x5a, 0xe8, 0x5a, 0xd9, 0x21, 0x4e, 0x16, 0x23, 0xfb, 0xde, 0xa5, 0x45, 0xbc,
	0x2d, 0xfd, 0x67, 0xa4, 0x17, 0x6f, 0xc0, 0x6b, 0x3e, 0xc0, 0x63, 0x70, 0x37, 0xd1, 0x66, 0x15,
	0x1c, 0xa1, 0x07, 0xbd, 0xe8, 0x63, 0xe0, 0xe0, 0x04, 0xfc, 0x4d, 0xf4, 0x79, 0x7b, 0x11, 0x7d,
	0xd9, 0xbc, 0x0f, 0x7a, 0xe8, 0xc3, 0x60, 0xc5, 0x79, 0xc4, 0x83, 0xfe, 0xe2, 0x97, 0x03, 0x0f,
	0x96, 0x95, 0x90, 0x89, 0xd1, 0x50, 0x6b, 0xa2, 0xeb, 0x4b, 0x92, 0x37, 0xd9, 0x37, 0xc2, 0x35,
	0x8c, 0x6f, 0x3b, 0x89, 0xac, 0x79, 0xf0, 0xdf, 0x0b, 0x3d, 0x7e, 0x74, 0xa0, 0xd2, 0x2c, 0x1a,
	0x1e, 0xbd, 0x72, 0x70, 0x05, 0xe3, 0xdb, 0x26, 0xb4, 0x42, 0x07, 0xec, 0x6b, 0x85, 0x0e, 0x39,
	0x16, 0x1e, 0x2d, 0x87, 0x5f, 0x07, 0x71, 0x9a, 0xee, 0xe2, 0xd8, 0xb3, 0x3f, 0xc6, 0xeb, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x51, 0x6d, 0x2a, 0x21, 0x2e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoardgamesGeekServiceClient is the client API for BoardgamesGeekService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoardgamesGeekServiceClient interface {
	GetGamesList(ctx context.Context, in *GetGamesListRequest, opts ...grpc.CallOption) (BoardgamesGeekService_GetGamesListClient, error)
	FindGameById(ctx context.Context, in *FindGameByIdRequest, opts ...grpc.CallOption) (*FindGameByIdResponse, error)
}

type boardgamesGeekServiceClient struct {
	cc *grpc.ClientConn
}

func NewBoardgamesGeekServiceClient(cc *grpc.ClientConn) BoardgamesGeekServiceClient {
	return &boardgamesGeekServiceClient{cc}
}

func (c *boardgamesGeekServiceClient) GetGamesList(ctx context.Context, in *GetGamesListRequest, opts ...grpc.CallOption) (BoardgamesGeekService_GetGamesListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BoardgamesGeekService_serviceDesc.Streams[0], "/bgg.BoardgamesGeekService/GetGamesList", opts...)
	if err != nil {
		return nil, err
	}
	x := &boardgamesGeekServiceGetGamesListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BoardgamesGeekService_GetGamesListClient interface {
	Recv() (*GetGamesListResponse, error)
	grpc.ClientStream
}

type boardgamesGeekServiceGetGamesListClient struct {
	grpc.ClientStream
}

func (x *boardgamesGeekServiceGetGamesListClient) Recv() (*GetGamesListResponse, error) {
	m := new(GetGamesListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boardgamesGeekServiceClient) FindGameById(ctx context.Context, in *FindGameByIdRequest, opts ...grpc.CallOption) (*FindGameByIdResponse, error) {
	out := new(FindGameByIdResponse)
	err := c.cc.Invoke(ctx, "/bgg.BoardgamesGeekService/FindGameById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardgamesGeekServiceServer is the server API for BoardgamesGeekService service.
type BoardgamesGeekServiceServer interface {
	GetGamesList(*GetGamesListRequest, BoardgamesGeekService_GetGamesListServer) error
	FindGameById(context.Context, *FindGameByIdRequest) (*FindGameByIdResponse, error)
}

// UnimplementedBoardgamesGeekServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBoardgamesGeekServiceServer struct {
}

func (*UnimplementedBoardgamesGeekServiceServer) GetGamesList(req *GetGamesListRequest, srv BoardgamesGeekService_GetGamesListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetGamesList not implemented")
}
func (*UnimplementedBoardgamesGeekServiceServer) FindGameById(ctx context.Context, req *FindGameByIdRequest) (*FindGameByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindGameById not implemented")
}

func RegisterBoardgamesGeekServiceServer(s *grpc.Server, srv BoardgamesGeekServiceServer) {
	s.RegisterService(&_BoardgamesGeekService_serviceDesc, srv)
}

func _BoardgamesGeekService_GetGamesList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetGamesListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoardgamesGeekServiceServer).GetGamesList(m, &boardgamesGeekServiceGetGamesListServer{stream})
}

type BoardgamesGeekService_GetGamesListServer interface {
	Send(*GetGamesListResponse) error
	grpc.ServerStream
}

type boardgamesGeekServiceGetGamesListServer struct {
	grpc.ServerStream
}

func (x *boardgamesGeekServiceGetGamesListServer) Send(m *GetGamesListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BoardgamesGeekService_FindGameById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindGameByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardgamesGeekServiceServer).FindGameById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgg.BoardgamesGeekService/FindGameById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardgamesGeekServiceServer).FindGameById(ctx, req.(*FindGameByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoardgamesGeekService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bgg.BoardgamesGeekService",
	HandlerType: (*BoardgamesGeekServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindGameById",
			Handler:    _BoardgamesGeekService_FindGameById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetGamesList",
			Handler:       _BoardgamesGeekService_GetGamesList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messages/bgg.proto",
}
